server:
  host: "0.0.0.0" # 服务器IP
  port: "8080" # 项目端口

url:
  logo: "http://127.0.0.1/logo.png" # 项目图标
  issue: "http://127.0.0.1:8075/#/task/detail/%d/%d/%s" # 发送邮件的具体资源访问连接
  avatar: "http://127.0.0.1:8081/%s" # 用户头像

mysql:
  dbHost: "mysql" # 数据库所在服务器IP
  dbPort: "3306" # 数据库端口
  dbName: "mydb" # 数据库DB名称
  userName: "root" # 数据库用户名称
  password: "secret" # 数据库用户密码
  charset: "utf8mb4" # 数据编码格式
  autoMigrate: "yes" # AutoMigrate功能用于是否自动迁移ORM模式

mongo:
  mongoUrl: "mongodb://root:example@mongodb:27017/mark3?authSource=admin"
  mongoDataBase: "mark3"


redis:
  redisDbName: 0 # redisDb名称
  redisHost: "redis" # redisDb所在服务器IP
  redisPort: "6379" # redisDb端口
  redisPassword: "" # redisDb密码
  redisNetwork: "tcp" # redisDb连接方式


upload:
  host: "127.0.0.1" # 上传文件服务器IP
  port: "8081" # 文件上传端口
  size: 50000000000 # 上传文件大小限制
  path: "/www/mark3_server_upload" # 文件存储地址
  imageExt: "jpg,jpeg,png,gif" # 支持图片上传的格式
  allExt: "txt,pdf,doc,docx,ppt,pptx,csv,xlsx,xls,json,xml,jpg,jpeg,png,gif" # 支持其他上传的文件格式
  needTransformed2PDFExt: "ppt,pptx" # 需要转换为PDF格式的文件
  needTransformed2EndX: "doc,xls" # 提升文本和excel的文件格式

smtp:
  host: "smtp.qq.com" # smtp的邮箱服务类型
  port: 465 # 邮箱端口
  username: "" # 发送邮件的邮箱账户
  password: "" # 发送邮件的邮箱密码
  from: "" # 发件人邮箱
  isOpen: "yes" # 是否开通由服务触发发送

rabbit:
  host: "rabbitmq" # rabbit 服务部署的IP
  port: "5672" # rabbit 服务端口
  username: "guest" # 账号
  password: "guest" # 密码

libreoffice:
  version: "libreoffice" # libreoffice linux安装版本号
